version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: vanguard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vanguard
      POSTGRES_PASSWORD: ${DB_PASSWORD:-vanguard_secure_password}
      POSTGRES_DB: vanguard_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vanguard"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vanguard-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_secure_password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vanguard-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://vanguard:${DB_PASSWORD:-vanguard_secure_password}@postgres:5432/vanguard_production
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_secure_password}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      JWT_EXPIRES_IN: 7d
      REFRESH_TOKEN_EXPIRES_IN: 30d
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads:/app/uploads
      - ml_models:/app/services/ml/models
    ports:
      - "3000:3000"
    command: npm run start:prod

  # Frontend Web App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
    container_name: vanguard-frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - frontend_dist:/usr/share/nginx/html

  # ML Worker (for background processing)
  ml-worker:
    build:
      context: ./server
      dockerfile: Dockerfile.worker
    container_name: vanguard-ml-worker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://vanguard:${DB_PASSWORD:-vanguard_secure_password}@postgres:5432/vanguard_production
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_secure_password}@redis:6379
      TENSORFLOW_BACKEND: cpu
    volumes:
      - ./server:/app
      - /app/node_modules
      - ml_models:/app/services/ml/models
    command: npm run worker

  # Backup Service
  backup:
    image: postgres:14-alpine
    container_name: vanguard-backup
    depends_on:
      - postgres
    environment:
      PGPASSWORD: ${DB_PASSWORD:-vanguard_secure_password}
    volumes:
      - ./backups:/backups
      - ./deploy/backup.sh:/backup.sh
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        echo "0 2 * * * /backup.sh" | crontab -
        crond -f

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  uploads:
    driver: local
  ml_models:
    driver: local
  frontend_dist:
    driver: local

networks:
  default:
    name: vanguard-network
    driver: bridge